### ISSUE TITLE
Set AppImage builds and deploy to GitHub

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/SteamCAD#1]
### TODO

- [x] Setup Travis CI & GitHub (tokens & permissions)
- [ ] Configure `.travis.yml` (need help!)
  - [x] https://github.com/Symbian9/SteamCAD/blob/master/.travis.yml
- [ ] Add pull request to original repo
  - [ ] https://github.com/oskardolch/SteamCAD/blob/master/.travis.yml

### REFERENCE

- https://github.com/appimage/appimagekit
- https://github.com/probonopd/linuxdeployqt
- https://github.com/probonopd/uploadtool
